# Generated by Django 6.0.4 on 2026-04-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
    ]
